CREATE TABLE IF NOT EXISTS flight_prices_raw (
    airline VARCHAR(255),
    source_airport_code VARCHAR(10),
    source_airport_name VARCHAR(255),
    destination_airport_code VARCHAR(10),
    destination_airport_name VARCHAR(255),
    departure_datetime VARCHAR(100),
    arrival_datetime VARCHAR(100),
    duration_hrs DECIMAL(10, 4),
    stopovers VARCHAR(50),
    aircraft_type VARCHAR(100),
    travel_class VARCHAR(50),
    booking_source VARCHAR(100),
    base_fare_bdt DECIMAL(15, 4),
    tax_surcharge_bdt DECIMAL(15, 4),
    total_fare_bdt DECIMAL(15, 4),
    seasonality VARCHAR(50),
    days_before_departure INT,
    ingestion_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);